[package]
name = "rcli"
authors = ["Jeff Morrison <lbljeffmo@gmail.com>"]
description = "A maximally declarative, build-time CLI parser generator."
edition = "2018"
license = "MIT"
version = "0.0.0"

[dependencies]
